### ISSUE TITLE
GPLayer doesn't seem to support multiple input units

### ISSUE THREAD

**Issue by dtchang** [secondmind-labs/GPflux#36]
Using the "Hybrid Deep GP models: ..." tutorial, when I changed
        tf.keras.layers.Dense(1, activation="linear"),
to
        tf.keras.layers.Dense(2, activation="linear"),
I got an error, same as reported in #27.

I then set a Zero mean function, as suggested in #27:
    gp_layer = gpflux.layers.GPLayer(
        kernel, inducing_variable, num_data=num_data, num_latent_gps=output_dim,
        mean_function=gpflow.mean_functions.Zero()
    ),
I got a different error.

**Comment by st--** [comment]
Hi @dtchang, it seems like you want to increase the *input* dimensionality of the GP by increasing the number of outputs of the underlying neural network, is that correct? note that the InducingPoints inducing_variable defined in the previous cell [3] is constructed to live in a 1D space, so this won't be compatible with the 2D output from the neural network. You could construct a 2D grid of inducing points instead. Does that resolve your issue? If not, please provide more details & error messages!

**Comment by dtchang** [comment]
In general, one only needs to specify the output dimension for a Keras layer, not the input dimension since the input dimension is automatically determined by the output dimension of the previous layer. TFP layers honor this. Shouldn't GPLayer honor this to be useful in building hybrid models, or maybe even DGP models? (There is no documentation on the usage expectation, patterns and constraints for GPLayer.)

**Comment by vdutor** [comment]
Hi @dtchang, it would indeed be possible to determine the input dimensionality of the GP and automatically create inducing points with the right dimension. However, in this first version of GPflux we decided to leave as much initialisation as possible to the user. I appreciate that this makes the code more verbose and less automatic, but it does give a user more control to construct non-standard (deep) GP models using, for example, interdomain inducing features. I would very much welcome a PR that addresses this problem though.
