### ISSUE TITLE
Add version upper bound before adjust gpflow>=2.6

### ISSUE THREAD

**Issue by zjowowen** [secondmind-labs/GPflux#83]
**Describe the bug**
GPflow>=2.6 seems to change the way to calculate likelihood p(Y|F,X) from by using F and Y to by using X, F and Y.
I guess this change would be incompatible to the current gpflux develop branch.

**To reproduce**
Steps to reproduce the behaviour:
1. git clone https://github.com/secondmind-labs/GPflux.git
2. pip install -e .
3. python ./gpflux/docs/notebooks/intro.py

An error will occur at Line 99.

**System information**
 - OS: Ubuntu20.04
 - Python version: 3.9.13
 - GPflux version: 
develop branch [f95e1cb](https://github.com/secondmind-labs/GPflux/commit/f95e1cbf5da84bf7fd49abc8af156827d01edeea)
 - TensorFlow version: 2.8.3
 - GPflow version: 2.6.1

**Additional context**
It would be ok if switching to gpflow==2.5.2

**Comment by hsvalladares** [comment]
Hi zjowowen. Thanks for raising this point. I am also facing the same issue. I am trying to run the other tutorials and they fail on that point. What would be the solution to overcome this issue?

**Comment by zjowowen** [comment]
Hi, hsvalladares. You can downgrade to gpflow==2.5.2 by pip install.
Or, you can try a developing branch by Jesnie, https://github.com/secondmind-labs/GPflux/tree/jesper/gpflow260
It seems to work, but I am not sure because it has not been merged yet.

**Comment by hsvalladares** [comment]
Hi zjowowen. Thanks for your suggestion. gpflow==2.5.2 works perfectly!

**Comment by st--** [comment]
This was an unfortunate backwards-compatibility-breaking change upstream in GPflow. GPflux has subsequently been adjusted in https://github.com/secondmind-labs/GPflux/pull/84 , and released in 0.3.1. Closing this issue as it's no longer applicable to the latest version.
